include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    avoid_print: false
    curly_braces_in_flow_control_structures: true
