name: bladenight_app_flutter
description: Bladenight App

publish_to: 'none'
version: 1.24.05

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.2.1
  app_links: 4.0.1
  archive: ^3.3.7
  asset_fill: ^1.1.0
  barcode_widget: ^2.0.2
  cached_network_image: ^3.3.1
  convert: ^3.1.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.4
  dart_mappable: ^4.2.0
  device_info_plus: ^10.0.1
  dio: ^5.4.1
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.1
  encrypt: ^5.0.1
  extended_text: ^13.0.0
  firebase_core: ^2.27.2
  firebase_crashlytics: ^3.4.20
  flex_color_picker: ^3.4.0
  flutter:
    sdk: flutter
  flutter_background_geolocation: ^4.12.0
  flutter_cache_manager: ^3.3.0
  flutter_device_type: ^0.4.0
  flutter_email_sender: ^6.0.1
  flutter_launcher_icons: ^0.13.1

  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.3.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.4
  flutter_map_marker_popup: ^6.1.2
  flutter_native_splash: ^2.3.0
  flutter_nearby_connections: ^1.1.2
  #to owner waiting for update
  #flutter_platform_alert:
  #  git:
  #    url: https://github.com/xunreal75/flutter_platform_alert.git
  #    branch: master
  flutter_riverpod: ^2.0.2
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.0.9
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: any
  internet_connection_checker_plus: ^2.3.0
  intl: any
  intro_slider: ^4.2.0
  latlong2: ^0.9.0
    #location:
    #git:
    #url: https://github.com/fairuzmn/flutterlocation.git
    #ref: location-v5.5.0.0-dev.9-fix
  #path: packages/location
  #geolocator:
  #git:
  #url: https://github.com/Baseflow/flutter-geolocator.git
  #ref: location-v5.5.0.0-dev.9-fix
  #path: ../flutter-geolocator/geolocator
  #location: ^4.4.0

  location2: ^6.0.4
  logger: ^2.0.1
  lottie: ^3.1.0
  maps_toolkit: ^3.0.0
  modal_bottom_sheet: ^3.0.0
  #modal_bottom_sheet:
  #  git:
  #    url: https://github.com/followthemoney1/modal_bottom_sheet.git
  #    ref: main
  #    path: modal_bottom_sheet
  onesignal_flutter: ^5.1.4
  package_info_plus: ^6.0.0
  path_provider: ^2.0.15
  permission_handler: ^11.1.0
  popover: ^0.3.0
  quickalert: ^1.1.0
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  riverpod_context: ^0.3.0
  rxdart: ^0.27.4
  settings_ui: ^2.0.2
  share_plus: ^8.0.2
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0
  step_progress_indicator: ^1.0.2
  sticky_headers: ^0.3.0+2
  synchronized: ^3.1.0+1
  timezone: any
  #uni_links: ^0.5.1
  #uni_links2: #Download from https://github.com/xunreal75/uni_links2.git and save to root
  #path: ../uni_links/uni_links/
  universal_io: ^2.2.0
  url_launcher: ^6.1.10
  vector_math: ^2.1.4
  #wakelock: ^0.6.2
  wakelock:
    git:
      url: https://github.com/xunreal75/wakelock.git
      path: wakelock/
      ref: 7221e0c8ba4feee2625f00eb44b4f2824b4b0913
      #path: ../wakelock/wakelock
  web_socket_channel: ^2.4.4
  webview_flutter: ^4.0.7

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint:
  dart_mappable_builder: ^4.2.2
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator:
  riverpod_lint:

analyzer:
  plugins:
    - custom_lint

dependency_overrides:
  # Remove when firebase_ui_firestore stops relying on 0.17.0.
  # https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_localizations/pubspec.yaml#L18
  #intl: ^0.19.0
  #location2:
  #path: ../flutterlocation/packages/location2
  wakelock_macos:
    git:
      url: https://github.com/xunreal75/wakelock.git
      path: wakelock_macos
      ref: 7221e0c8ba4feee2625f00eb44b4f2824b4b0913
  wakelock_platform_interface:
    git:
      url: https://github.com/xunreal75/wakelock.git
      path: wakelock_platform_interface
      ref: 7221e0c8ba4feee2625f00eb44b4f2824b4b0913
  wakelock_web:
    git:
      url: https://github.com/xunreal75/wakelock.git
      path: wakelock_web
      ref: 7221e0c8ba4feee2625f00eb44b4f2824b4b0913
  wakelock_windows:
    git:
      url: https://github.com/xunreal75/wakelock.git
      path: wakelock_windows
      ref: 7221e0c8ba4feee2625f00eb44b4f2824b4b0913


# can't compile mapper if generate is set to true --> solve it by set to false , clean and rebuild
flutter:
  generate: false
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/certs/
    - assets/html/
    - assets/images/
    - assets/images/instruction/
    - assets/iosStore/
    - assets/lottie/
    - assets/maptiles/
    - assets/maptiles/osday/
    - assets/maptiles/osday/10/
    - assets/maptiles/osday/10/544/
    - assets/maptiles/osday/10/545/
    - assets/maptiles/osday/11/
    - assets/maptiles/osday/11/1088/
    - assets/maptiles/osday/11/1089/
    - assets/maptiles/osday/11/1090/
    - assets/maptiles/osday/11/1091/
    - assets/maptiles/osday/12/
    - assets/maptiles/osday/12/2176/
    - assets/maptiles/osday/12/2177/
    - assets/maptiles/osday/12/2178/
    - assets/maptiles/osday/12/2179/
    - assets/maptiles/osday/12/2180/
    - assets/maptiles/osday/12/2181/
    - assets/maptiles/osday/12/2182/
    - assets/maptiles/osday/13/
    - assets/maptiles/osday/13/4352/
    - assets/maptiles/osday/13/4353/
    - assets/maptiles/osday/13/4354/
    - assets/maptiles/osday/13/4355/
    - assets/maptiles/osday/13/4356/
    - assets/maptiles/osday/13/4357/
    - assets/maptiles/osday/13/4358/
    - assets/maptiles/osday/13/4359/
    - assets/maptiles/osday/13/4360/
    - assets/maptiles/osday/13/4361/
    - assets/maptiles/osday/13/4362/
    - assets/maptiles/osday/13/4363/
    - assets/maptiles/osday/13/4364/
    - assets/maptiles/osday/13/4365/
    - assets/maptiles/osday/14/
    - assets/maptiles/osday/14/8705/
    - assets/maptiles/osday/14/8706/
    - assets/maptiles/osday/14/8707/
    - assets/maptiles/osday/14/8708/
    - assets/maptiles/osday/14/8709/
    - assets/maptiles/osday/14/8710/
    - assets/maptiles/osday/14/8711/
    - assets/maptiles/osday/14/8712/
    - assets/maptiles/osday/14/8713/
    - assets/maptiles/osday/14/8714/
    - assets/maptiles/osday/14/8715/
    - assets/maptiles/osday/14/8716/
    - assets/maptiles/osday/14/8717/
    - assets/maptiles/osday/14/8718/
    - assets/maptiles/osday/14/8719/
    - assets/maptiles/osday/14/8720/
    - assets/maptiles/osday/14/8721/
    - assets/maptiles/osday/14/8722/
    - assets/maptiles/osday/14/8723/
    - assets/maptiles/osday/14/8724/
    - assets/maptiles/osday/14/8725/
    - assets/maptiles/osday/14/8726/
    - assets/maptiles/osday/14/8727/
    - assets/maptiles/osday/14/8728/
    - assets/maptiles/osday/14/8729/
    - assets/maptiles/osday/14/8730/
    - assets/maptiles/osday/15/
    - assets/maptiles/osday/15/17410/
    - assets/maptiles/osday/15/17411/
    - assets/maptiles/osday/15/17412/
    - assets/maptiles/osday/15/17413/
    - assets/maptiles/osday/15/17414/
    - assets/maptiles/osday/15/17415/
    - assets/maptiles/osday/15/17416/
    - assets/maptiles/osday/15/17417/
    - assets/maptiles/osday/15/17418/
    - assets/maptiles/osday/15/17419/
    - assets/maptiles/osday/15/17420/
    - assets/maptiles/osday/15/17421/
    - assets/maptiles/osday/15/17422/
    - assets/maptiles/osday/15/17423/
    - assets/maptiles/osday/15/17424/
    - assets/maptiles/osday/15/17425/
    - assets/maptiles/osday/15/17426/
    - assets/maptiles/osday/15/17427/
    - assets/maptiles/osday/15/17428/
    - assets/maptiles/osday/15/17429/
    - assets/maptiles/osday/15/17430/
    - assets/maptiles/osday/15/17431/
    - assets/maptiles/osday/15/17432/
    - assets/maptiles/osday/15/17433/
    - assets/maptiles/osday/15/17434/
    - assets/maptiles/osday/15/17435/
    - assets/maptiles/osday/15/17436/
    - assets/maptiles/osday/15/17437/
    - assets/maptiles/osday/15/17438/
    - assets/maptiles/osday/15/17439/
    - assets/maptiles/osday/15/17440/
    - assets/maptiles/osday/15/17441/
    - assets/maptiles/osday/15/17442/
    - assets/maptiles/osday/15/17443/
    - assets/maptiles/osday/15/17444/
    - assets/maptiles/osday/15/17445/
    - assets/maptiles/osday/15/17446/
    - assets/maptiles/osday/15/17447/
    - assets/maptiles/osday/15/17448/
    - assets/maptiles/osday/15/17449/
    - assets/maptiles/osday/15/17450/
    - assets/maptiles/osday/15/17451/
    - assets/maptiles/osday/15/17452/
    - assets/maptiles/osday/15/17453/
    - assets/maptiles/osday/15/17454/
    - assets/maptiles/osday/15/17455/
    - assets/maptiles/osday/15/17456/
    - assets/maptiles/osday/15/17457/
    - assets/maptiles/osday/15/17458/
    - assets/maptiles/osday/15/17459/
    - assets/maptiles/osday/15/17460/
    - assets/maptiles/osday/5/
    - assets/maptiles/osday/5/17/
    - assets/maptiles/osday/6/
    - assets/maptiles/osday/6/34/
    - assets/maptiles/osday/7/
    - assets/maptiles/osday/7/68/
    - assets/maptiles/osday/8/
    - assets/maptiles/osday/8/136/
    - assets/maptiles/osday/9/
    - assets/maptiles/osday/9/272/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: Localize # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en
  # arb_dir: l10n # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#aaaaaa"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/images/skatechildmunichicon_256.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  branding: assets/images/skatemunich.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#222222"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/skatechildmunichicon_256.png
  branding_dark: assets/images/skatemunich.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle in the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # Splash screen background color.
  #color: "#42a5f5"

  # App icon background color.
  #icon_background_color: "#111111"

  # The branding property allows you to specify an image used as branding in the splash screen.
  #branding: assets/dart.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  # apply when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  ios: false
  web: false

  # Platform specific images can be specified with the following parameters, which will override
  # the respective parameter.  You may specify all, selected, or none of these parameters:
  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.gif
  #branding_dark_ios: assets/dart_dark-ios.gif

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: [SystemUiOverlay.bottom, SystemUiOverlay.top], );
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'